### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cxistiro**

### CODE REVIEW

**Comment by Cxistiro** [comment]
not sure if monterey is in macrecovery yet but if not it'll prob be out very very soon anyways

**Comment by Cxistiro** [comment]
also I did this because I was bored so yeah

**Comment by Cxistiro** [comment]
Added macOS Monterey airport itlwm kext found here https://github.com/OpenIntelWireless/itlwm/issues/617

**Comment by Cxistiro** [comment]
I think I made the installer guide too long but yea I just did this for fun I guess

**Comment by racka98** [comment]
Did you update to macOS 12? 

Also when you are done tell me so i can merge the changes

**Comment by Cxistiro** [comment]
I am done but you should probably change the macOS about screenshot because it’s bit blurry and I don’t have access to the think pad right now but I did test everything yesterday

**Comment by Cxistiro** [comment]
There’s probably a lot to change but I did my best for fun

**Comment by racka98** [comment]
> There’s probably a lot to change but I did my best for fun

No problem. You can always add stuff later

**Pull request merged**
